import { type NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  try {
    const { prompt } = await request.json()

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 })
    }

    // Check for API key
    const apiKey = process.env.GOOGLE_API_KEY
    if (!apiKey) {
      return NextResponse.json(
        {
          error: "Google API key not configured",
          details: "Please add GOOGLE_API_KEY to your environment variables",
        },
        { status: 500 },
      )
    }

    console.log("[v0] Making request to Google Gemini API...")

    const systemPrompt = `You are an expert Next.js developer. Generate a complete, production-ready Next.js project based on the user's request.

IMPORTANT: You MUST respond with ONLY a valid JSON object in this exact format:
{
  "explanation": "Brief explanation of what you built",
  "files": [
    {
      "name": "app/page.tsx",
      "content": "// Complete React component code here"
    },
    {
      "name": "components/ComponentName.tsx", 
      "content": "// Additional component code if needed"
    }
  ]
}

Requirements:
- Always include app/page.tsx as the main file
- Use TypeScript and Tailwind CSS
- Make components responsive and accessible
- Include proper imports and exports
- Generate complete, working code that can be rendered
- Do not include any markdown formatting, just pure JSON`

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: `${systemPrompt}\n\nUser request: ${prompt}`,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 8000,
          },
        }),
      },
    )

    console.log("[v0] Response status:", response.status)

    if (!response.ok) {
      const errorText = await response.text()
      console.error("[v0] Gemini API error:", errorText)
      return NextResponse.json(
        {
          error: "Google Gemini API error",
          details: `Status ${response.status}: ${errorText}`,
        },
        { status: response.status },
      )
    }

    const data = await response.json()
    console.log("[v0] Raw response received")

    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      console.error("[v0] No generated text in response")
      return NextResponse.json({ error: "No content generated by Gemini" }, { status: 500 })
    }

    console.log("[v0] Generated text length:", generatedText.length)

    let cleanedJson = generatedText.trim()

    // Remove markdown code blocks if present
    if (cleanedJson.startsWith("```json")) {
      cleanedJson = cleanedJson.replace(/^```json\s*/, "").replace(/\s*```$/, "")
    } else if (cleanedJson.startsWith("```")) {
      cleanedJson = cleanedJson.replace(/^```\s*/, "").replace(/\s*```$/, "")
    }

    // Parse the JSON
    let parsedResponse
    try {
      parsedResponse = JSON.parse(cleanedJson)
      console.log("[v0] Successfully parsed JSON response")
    } catch (parseError) {
      console.error("[v0] JSON parse error:", parseError)
      console.log("[v0] Attempting to extract JSON from text...")

      // Try to find JSON object in the text
      const jsonMatch = cleanedJson.match(/\{[\s\S]*\}/)
      if (jsonMatch) {
        try {
          parsedResponse = JSON.parse(jsonMatch[0])
          console.log("[v0] Successfully extracted and parsed JSON")
        } catch (extractError) {
          console.error("[v0] Failed to parse extracted JSON:", extractError)
          return NextResponse.json(
            {
              error: "Invalid JSON response from AI",
              details: "Could not parse the generated response",
            },
            { status: 500 },
          )
        }
      } else {
        return NextResponse.json(
          {
            error: "No valid JSON found in response",
            details: "AI did not return properly formatted JSON",
          },
          { status: 500 },
        )
      }
    }

    if (!parsedResponse.files || !Array.isArray(parsedResponse.files)) {
      console.error("[v0] Invalid response structure - missing files array")
      return NextResponse.json(
        {
          error: "Invalid response structure",
          details: "Response must contain a files array",
        },
        { status: 500 },
      )
    }

    // Ensure we have a main page file
    const hasMainPage = parsedResponse.files.some((file: any) => file.name === "app/page.tsx")
    if (!hasMainPage) {
      console.log("[v0] Adding missing app/page.tsx file")
      parsedResponse.files.unshift({
        name: "app/page.tsx",
        content: `export default function Page() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-2xl font-bold text-gray-900">Generated Component</h1>
        <p className="text-gray-600 mt-2">Your component has been generated successfully.</p>
      </div>
    </div>
  )
}`,
      })
    }

    console.log("[v0] Returning processed response with", parsedResponse.files.length, "files")

    return NextResponse.json({
      explanation: parsedResponse.explanation || "Generated Next.js project successfully",
      files: parsedResponse.files,
    })
  } catch (error) {
    console.error("[v0] API route error:", error)
    return NextResponse.json(
      {
        error: "Internal server error",
        details: error instanceof Error ? error.message : "Unknown error occurred",
      },
      { status: 500 },
    )
  }
}
